### ISSUE TITLE
Connect test on Ubuntu shows 95 missing dependencies. Most of these are inaccurate.

### ISSUE THREAD

**Issue by sjimellor-jr** [jumpingrivers/audit.connect#22]
- Build a new Connect server on Ubuntu 22.04.
- Install every dependency listed on https://packagemanager.posit.co/client/#/repos/cran/setup?distribution=ubuntu-22.04&r_environment=ide under "Install System Requirements"
- Run an audit from Workbench against Connect

Connect test on Ubuntu shows 95 missing dependencies. Most of these are inaccurate.

```r
audit.connect::check()
```

The list includes `make` as missing, and yet:

```
# apt-cache policy make
make:
  Installed: 4.3-4.1build1
  Candidate: 4.3-4.1build1
  Version table:
 *** 4.3-4.1build1 500
        500 http://mirrors.digitalocean.com/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by csgillespie** [comment]
Issue is 

```
  audit.base::check_sys_deps(rtn$os_release, rtn$libs, debug_level)
```
libs need to be cleaned. 

Solution: 
 * small refactor in audit.base
 * clean
 * pass cleaned output to funciton

**Comment by csgillespie** [comment]
Fixed in https://github.com/jumpingrivers/audit.connect/pull/23
